name: Build binaries for release
on:
  workflow_dispatch:

jobs:
  build-android:
    name: build binaries for android
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - x86
          - armv7-a
          - armv8-a
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run autogen
        shell: bash
        run: |
          ./autogen.sh -s
      - name: build binaries
        shell: bash
        run: |
          ./dist-build/android-${{ matrix.arch }}.sh
      - name: upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: android-${{ matrix.arch }}
          path: libsodium-android-${{ matrix.arch }}*
  build-linux:
    name: build binaries for linux
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x86_64
          - armv7-a
          - armv8-a+crypto+aes
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run autogen
        shell: bash
        run: |
          ./autogen.sh -s
      - name: run configure
        shell: bash
        run: |
          env CFLAGS="-Os -march=${{ matrix.arch }}" ./configure --prefix=$(pwd)/libsodium-${{ matrix.arch }}
      - name: build binaries
        shell: bash
        run: |
          NPROCESSORS=$(getconf NPROCESSORS_ONLN 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
          make clean && \
            make -j${PROCESSORS} install
      - name: upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.arch }}
          path: libsodium-${{ matrix.arch }}
  build-windows:
    name: build binaries for windows
    strategy:
      fail-fast: false
      matrix:
        arch:
          - win32
          - win64
    runs-on: windows-latest
    steps:
      - name: install 32bit complier
        shell: bash
        run: |
          apt-get update
          apt-get install gcc-mingw-w64-i686
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run autogen
        shell: bash
        run: |
          ./autogen.sh -s
      - name: build windows binaries
        shell: bash
        run: |
          ./dist-build/msys2-${{ matrix.arch }}.sh
      - name: upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.arch }}
          path: libsodium-${{ matrix.arch }}
  build-apple:
    name: build binaries for apple
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: build binaries
        shell: bash
        run: |
          ./dist-build/apple-xcframework.sh
      - name: upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: apple
          path: libsodium-apple
